const passport = require('passport');
const User = require('../models/user');
const dotenv = require('dotenv');

dotenv.config();

exports.getRadicals = async (req, res) => {
  try {
    res.render('radicals', { user: req.user });
  } catch (err) {
    console.error(err);
    res.status(500).send('Server Error');
  }
};

exports.getRadicalsList = async (req, res) => {
  try {
    const radicalsEasy = [
      { Radical: "一", Reading: "いち", Meaning: "one, horizontal stroke" },
      { Radical: "⼁", Reading: "たてぼう", Meaning: "vertical stroke" },
      { Radical: "⼂", Reading: "てん", Meaning: "dot" },
      { Radical: "⼃", Reading: "の", Meaning: "diagonal sweeping stroke" },
      { Radical: "", Reading: "のかんむり", Meaning: "diagonal sweeping stroke" },
      { Radical: "⼄", Reading: "おつ", Meaning: "the second" },
      { Radical: "⺃", Reading: "おつ", Meaning: "the second" },
      { Radical: "⼅", Reading: "はねぼう", Meaning: "vertical stroke with a hook" },
      { Radical: "⼆", Reading: "に", Meaning: "two" },
      { Radical: "⼇", Reading: "なべぶた", Meaning: "lid, top" },
      { Radical: "⼈", Reading: "ひと", Meaning: "person" },
      { Radical: "⺅", Reading: "にんべん", Meaning: "person" },
      { Radical: "𠆢", Reading: "ひとやね", Meaning: "person" },
      { Radical: "⼉", Reading: "ひとあし", Meaning: "human legs" },
      { Radical: "⼊", Reading: "いる", Meaning: "to enter" },
      { Radical: "⼋", Reading: "はち", Meaning: "eight" },
      { Radical: "", Reading: "はちがしら", Meaning: "eight" },
      { Radical: "⼌", Reading: "けいがまえ", Meaning: "to enclose" },
      { Radical: "⼍", Reading: "わかんむり", Meaning: "cover, crown" },
      { Radical: "⼎", Reading: "にすい", Meaning: "ice" },
      { Radical: "⼏", Reading: "きにょう", Meaning: "table" },
      { Radical: "⺇", Reading: "かぜかんむり", Meaning: "wind" },
      { Radical: "⼐", Reading: "かんにょう", Meaning: "container, open box" },
      { Radical: "⼑", Reading: "かたな", Meaning: "knife, sword" },
      { Radical: "⺉", Reading: "りっとう", Meaning: "knife, sword" },
      { Radical: "⼒", Reading: "ちから", Meaning: "power" },
      { Radical: "⼓", Reading: "つつみがまえ", Meaning: "to wrap" },
      { Radical: "⼔", Reading: "さじ", Meaning: "spoon" },
      { Radical: "⼕", Reading: "はこがまえ", Meaning: "box" },
      { Radical: "⼖", Reading: "かくしがまえ", Meaning: "to conceal, hide" },
      { Radical: "⼗", Reading: "じゅう", Meaning: "ten" },
      { Radical: "⼘", Reading: "ぼく", Meaning: "oracle" },
      { Radical: "⼙", Reading: "ふしづくり", Meaning: "stamp, seal" },
      { Radical: "⼚", Reading: "がんだれ", Meaning: "cliff" },
      { Radical: "⼛", Reading: "む", Meaning: "private, Katakana Mu" },
      { Radical: "⼜", Reading: "また", Meaning: "again, right hand" },
      { Radical: "⼝", Reading: "くち", Meaning: "mouth" },
      { Radical: "", Reading: "くちへん", Meaning: "mouth" },
      { Radical: "⼞", Reading: "くにがまえ", Meaning: "border, territorial boundaries" },
      { Radical: "⼟", Reading: "つち", Meaning: "earth" },
      { Radical: "", Reading: "つちへん", Meaning: "earth" },
      { Radical: "⼠", Reading: "さむらい", Meaning: "man, scholar, samurai" },
      { Radical: "", Reading: "さむらいかんむり", Meaning: "man, scholar, samurai" },
      { Radical: "⼡", Reading: "のまた", Meaning: "to follow" },
      { Radical: "⼢", Reading: "なつあし", Meaning: "to go slowly" },
      { Radical: "⼣", Reading: "ゆうべ", Meaning: "evening" },
      { Radical: "⼤", Reading: "だい", Meaning: "large, big" },
      { Radical: "⼥", Reading: "おんな", Meaning: "woman" },
      { Radical: "", Reading: "おんなへん", Meaning: "woman" },
      { Radical: "⼦", Reading: "こ", Meaning: "child, son" },
      { Radical: "", Reading: "こへん", Meaning: "child, son" },
      { Radical: "⼧", Reading: "うかんむり", Meaning: "roof, house" },
      { Radical: "⼨", Reading: "すん", Meaning: "inch, (2.25 cm)" },
      { Radical: "", Reading: "すんづくり", Meaning: "inch, (2.25 cm)" },
      { Radical: "⼩", Reading: "しょう", Meaning: "small" },
      { Radical: "⺌", Reading: "しょうかんむり", Meaning: "small" },
      { Radical: "⺐", Reading: "だいのまげあし", Meaning: "lame leg" },
      { Radical: "⼫", Reading: "しかばね", Meaning: "corpse, awning" },
      { Radical: "⼬", Reading: "くさのめ", Meaning: "sprout" },
      { Radical: "⼭", Reading: "やま", Meaning: "mountain" },
      { Radical: "", Reading: "やまへん", Meaning: "mountain" },
      { Radical: "", Reading: "やまかんむり", Meaning: "mountain" },
      { Radical: "⼮", Reading: "まがりがわ", Meaning: "winding river" },
      { Radical: "川", Reading: "さんぼんがわ", Meaning: "river" },
      { Radical: "⼯", Reading: "たくみ", Meaning: "work, carpenter, skill" },
      { Radical: "", Reading: "たくみへん", Meaning: "work, carpenter, skill" },
      { Radical: "⼰", Reading: "おのれ", Meaning: "self" },
      { Radical: "⼱", Reading: "はば", Meaning: "cloth" },
      { Radical: "", Reading: "はばへん", Meaning: "cloth" },
      { Radical: "⼲", Reading: "かん", Meaning: "to dry, shield" },
      { Radical: "⺓", Reading: "いとがしら", Meaning: "young, slight" },
      { Radical: "⼴", Reading: "まだれ", Meaning: "slanting roof" },
      { Radical: "⼵", Reading: "えんにょう", Meaning: "to move, stretch" },
      { Radical: "⼶", Reading: "にじゅうあし", Meaning: "folded hands" },
      { Radical: "⼷", Reading: "いぐるみ", Meaning: "javelin" },
      { Radical: "⼸", Reading: "ゆみ", Meaning: "bow （in archery）" },
      { Radical: "", Reading: "ゆみへん", Meaning: "bow （in archery）" },
      { Radical: "⼹", Reading: "けいがしら", Meaning: "pig’s head" },
      { Radical: "⺕", Reading: "けいがしら", Meaning: "pig’s head" },
      { Radical: "⺔", Reading: "けいがしら", Meaning: "pig’s head" },
      { Radical: "⼺", Reading: "さんづくり", Meaning: "hair-style, light rays" },
      { Radical: "⼻", Reading: "ぎょうにんべん", Meaning: "step, stride, street, to go" },
      { Radical: "⺾", Reading: "くさかんむり", Meaning: "grass" },
      { Radical: "⻌", Reading: "しんにょう", Meaning: "road, walk, to advance" },
      { Radical: "⻏", Reading: "おおざと", Meaning: "village, country, city" },
      { Radical: "⻖", Reading: "こざとへん", Meaning: "hill, mound" },
      { Radical: "⺍", Reading: "つ", Meaning: "Katakana Tsu" },
      { Radical: "⺖", Reading: "りっしんべん", Meaning: "heart, mind, spirit" },
      { Radical: "⺘", Reading: "てへん", Meaning: "hand" },
      { Radical: "⺡", Reading: "さんずい", Meaning: "water" },
      { Radical: "⺨", Reading: "けものへん", Meaning: "beast" }
  ];

    const radicalsHard = [
      { Radical: "⼼", Reading: "こころ", Meaning: "heart, mind, spirit" },
      { Radical: "⺗", Reading: "したごころ", Meaning: "heart, mind, spirit"},
      { Radical: "⼽", Reading: "ほこ", Meaning: "spear, weapon" },
      { Radical: "⼾", Reading: "と", Meaning: "door" },
      { Radical: "", Reading: "とだれ", Meaning: "door"},
      { Radical: "⼿", Reading: "て", Meaning: "hand" },
      { Radical: "⽀", Reading: "しにょう", Meaning: "branch" },
      { Radical: "⽁", Reading: "ぼくづくり", Meaning: "activity, to strike, hit" },
      { Radical: "⺙", Reading: "ぼくづくり", Meaning: "activity, to strike, hit"},
      { Radical: "⽂", Reading: "ぶん", Meaning: "literature, letters" },
      { Radical: "⽃", Reading: "ますづくり", Meaning: "big dipper, ladle, 18 liters" },
      { Radical: "⽄", Reading: "おのづくり", Meaning: "axe" },
      { Radical: "⽅", Reading: "ほう", Meaning: "direction, flag" },
      { Radical: "", Reading: "ほうへん", Meaning: "direction, flag"},
      { Radical: "⽆", Reading: "むにょう", Meaning: "not" },
      { Radical: "⽇", Reading: "ひ", Meaning: "sun, day, time" },
      { Radical: "", Reading: "ひへん", Meaning: "sun, day, time"},
      { Radical: "⽈", Reading: "ひらび", Meaning: "to say" },
      { Radical: "⽉", Reading: "つき", Meaning: "moon, month, period" },
      { Radical: "⺝", Reading: "つきへん", Meaning: "moon, month, period"},
      { Radical: "", Reading: "にくづき", Meaning: "meat, flesh"},
      { Radical: "⽊", Reading: "き", Meaning: "tree, wood" },
      { Radical: "", Reading: "きへん", Meaning: "tree, wood"},
      { Radical: "⽋", Reading: "あくび", Meaning: "to lack, yawn" },
      { Radical: "⽌", Reading: "とめる", Meaning: "to stop" },
      { Radical: "⽍", Reading: "がつ", Meaning: "death & dying, to decompose" },
      { Radical: "", Reading: "がつへん", Meaning: "death & dying, to decompose"},
      { Radical: "⽎", Reading: "るまた", Meaning: "lance shaft, action" },
      { Radical: "⽏", Reading: "なかれ", Meaning: "not, mother" },
      { Radical: "⽐", Reading: "くらべる", Meaning: "to compare" },
      { Radical: "⽑", Reading: "け", Meaning: "hair" },
      { Radical: "⽒", Reading: "うじ", Meaning: "family, clan" },
      { Radical: "⽓", Reading: "きがまえ", Meaning: "steam, air" },
      { Radical: "⽔", Reading: "みず", Meaning: "water" },
      { Radical: "⽕", Reading: "ひ", Meaning: "fire" },
      { Radical: "", Reading: "ひへん", Meaning: "fire"},
      { Radical: "⺣", Reading: "れっか", Meaning: "fire"},
      { Radical: "⽖", Reading: "つめ", Meaning: "claw, nail" },
      { Radical: "⺤", Reading: "つめかんむり", Meaning: "claw, nail"},
      { Radical: "爫", Reading: "つめかんむり", Meaning: "claw, nail"},
      { Radical: "⽗", Reading: "ちち", Meaning: "father" },
      { Radical: "⽘", Reading: "こう", Meaning: "to mix" },
      { Radical: "⽙", Reading: "しょうへん", Meaning: "split wood" },
      { Radical: "⽚", Reading: "かた", Meaning: "split wood" },
      { Radical: "", Reading: "かたへん", Meaning: "split wood"},
      { Radical: "", Reading: "きば", Meaning: "fang, canine tooth" },
      { Radical: "⽜", Reading: "うし", Meaning: "cow" },
      { Radical: "", Reading: "うしへん", Meaning: "cow"},
      { Radical: "⽝", Reading: "いぬ", Meaning: "dog" },
      { Radical: "", Reading: "おうへん", Meaning: "jewelry, jeweled king"},
      { Radical: "⺭", Reading: "しめすへん", Meaning: "altar, festival, religious service"},
      { Radical: "㓁", Reading: "あみがしら", Meaning: "net"},
      { Radical: "⺹", Reading: "おいかんむり", Meaning: "old, old-age"},
      { Radical: "⽞", Reading: "げん", Meaning: "darkness" },
      { Radical: "⽟", Reading: "たま", Meaning: "jewelry" },
      { Radical: "", Reading: "うり", Meaning: "melon" },
      { Radical: "⽡", Reading: "かわら", Meaning: "tile" },
      { Radical: "⽢", Reading: "あまい", Meaning: "sweet" },
      { Radical: "⽣", Reading: "うまれる", Meaning: "birth, to be born, live" },
      { Radical: "⽤", Reading: "もちいる", Meaning: "to use" },
      { Radical: "⽥", Reading: "た", Meaning: "rice paddy" },
      { Radical: "", Reading: "たへん", Meaning: "rice paddy" },
      { Radical: "⽦", Reading: "ひき", Meaning: "bolt of cloth" },
      { Radical: "⺪", Reading: "ひきへん", Meaning: "bolt of cloth" },
      { Radical: "⽧", Reading: "やまいだれ", Meaning: "sickness" },
      { Radical: "⽨", Reading: "はつがしら", Meaning: "outspread legs, departure" },
      { Radical: "⽩", Reading: "しろ", Meaning: "white" },
      { Radical: "", Reading: "はくへん", Meaning: "white" },
      { Radical: "⽪", Reading: "けがわ", Meaning: "skin, hide" },
      { Radical: "⽫", Reading: "さら", Meaning: "plate, bowl" },
      { Radical: "⽬", Reading: "め", Meaning: "eye" },
      { Radical: "", Reading: "めへん", Meaning: "eye" },
      { Radical: "", Reading: "よこめ", Meaning: "eye" },
      { Radical: "⽭", Reading: "ほこ", Meaning: "halberd" },
      { Radical: "", Reading: "ほこへん", Meaning: "halberd" },
      { Radical: "⽮", Reading: "や", Meaning: "arrow" },
      { Radical: "", Reading: "やへん", Meaning: "arrow" },
      { Radical: "⽯", Reading: "いし", Meaning: "stone" },
      { Radical: "", Reading: "いしへん", Meaning: "stone" },
      { Radical: "⽰", Reading: "しめす", Meaning: "altar, festival, religious service" },
      { Radical: "⽱", Reading: "じゅうのあし", Meaning: "footprint" },
      { Radical: "⽲", Reading: "のぎへん", Meaning: "grain" },
      { Radical: "⽳", Reading: "あな", Meaning: "hole, cave" },
      { Radical: "", Reading: "あなかんむり", Meaning: "hole, cave" },
      { Radical: "⽴", Reading: "たつ", Meaning: "to stand" },
      { Radical: "", Reading: "たつへん", Meaning: "to stand" },
      { Radical: "", Reading: "きば", Meaning: "fang, canine tooth" },
      { Radical: "", Reading: "きばへん", Meaning: "fang, canine tooth" },
      { Radical: "氺", Reading: "したみず", Meaning: "water" },
      { Radical: "⺫", Reading: "あみがしら", Meaning: "net" },
      { Radical: "𦉰", Reading: "あみがしら", Meaning: "net" },
      { Radical: "⻂", Reading: "ころもへん", Meaning: "clothing" },
      { Radical: "⺛", Reading: "むにょう", Meaning: "not" },
      { Radical: "⽵", Reading: "たけ", Meaning: "bamboo" },
      { Radical: "⺮", Reading: "たけかんむり", Meaning: "bamboo" },
      { Radical: "⽶", Reading: "こめ", Meaning: "rice" },
      { Radical: "", Reading: "こめへん", Meaning: "rice" },
      { Radical: "⽷", Reading: "いと", Meaning: "thread" },
      { Radical: "", Reading: "いとへん", Meaning: "thread" },
      { Radical: "⽸", Reading: "みずがめ", Meaning: "earthen jar" },
      { Radical: "⽹", Reading: "あみめ", Meaning: "net" },
      { Radical: "⽺", Reading: "ひつじ", Meaning: "sheep" },
      { Radical: "⺷", Reading: "ひつじ", Meaning: "sheep" },
      { Radical: "羽", Reading: "はね", Meaning: "feather, wing" },
      { Radical: "⽻", Reading: "はね", Meaning: "feather, wing" },
      { Radical: "⽼", Reading: "おいかんむり", Meaning: "old, old-age" },
      { Radical: "⽽", Reading: "しこうして", Meaning: "and also" },
      { Radical: "⽾", Reading: "らいすき", Meaning: "plow" },
      { Radical: "⽿", Reading: "みみ", Meaning: "ear" },
      { Radical: "", Reading: "みみへん", Meaning: "ear" },
      { Radical: "⾀", Reading: "ふでづくり", Meaning: "writing brush" },
      { Radical: "⾁", Reading: "にく", Meaning: "flesh, meat" },
      { Radical: "⾂", Reading: "しん", Meaning: "retainer, minister" },
      { Radical: "⾃", Reading: "みずから", Meaning: "self" },
      { Radical: "⾄", Reading: "いたる", Meaning: "to arrive, reach" },
      { Radical: "", Reading: "いたるへん", Meaning: "to arrive, reach" },
      { Radical: "⾅", Reading: "うす", Meaning: "mortar, quern" },
      { Radical: "⾆", Reading: "した", Meaning: "tongue" },
      { Radical: "⾇", Reading: "まいあし", Meaning: "contrary, to err" },
      { Radical: "⾈", Reading: "ふね", Meaning: "ship, boat" },
      { Radical: "", Reading: "ふねへん", Meaning: "ship, boat" },
      { Radical: "⾉", Reading: "こん", Meaning: "boundary" },
      { Radical: "⾊", Reading: "いろ", Meaning: "color" },
      { Radical: "⾋", Reading: "くさ", Meaning: "grass, plant" },
      { Radical: "⾌", Reading: "とらがしら", Meaning: "tiger" },
      { Radical: "⾍", Reading: "むし", Meaning: "worm, insect, bug" },
      { Radical: "", Reading: "むしへん", Meaning: "worm, insect, bug" },
      { Radical: "⾎", Reading: "ち", Meaning: "blood" },
      { Radical: "⾏", Reading: "ぎょうがまえ", Meaning: "to go" },
      { Radical: "⾐", Reading: "ころも", Meaning: "clothing" },
      { Radical: "⾑", Reading: "にし", Meaning: "cover, west" },
      { Radical: "⻃", Reading: "にし", Meaning: "cover, west" },
      { Radical: "⽠", Reading: "うり", Meaning: "melon" }
    ];
    const radicalsAdavnced = [
      { Radical: "⾒", Reading: "みる", Meaning: "to see" },
      { Radical: "⾓", Reading: "つの", Meaning: "horn, corner" },
      { Radical: "", Reading: "つのへん", Meaning: "horn, corner" },
      { Radical: "⾔", Reading: "げん", Meaning: "words, to speak, say" },
      { Radical: "", Reading: "ごんへん", Meaning: "words, to speak, say" },
      { Radical: "⾕", Reading: "たに", Meaning: "valley" },
      { Radical: "", Reading: "たにへん", Meaning: "valley" },
      { Radical: "⾖", Reading: "まめ", Meaning: "bean" },
      { Radical: "", Reading: "まめへん", Meaning: "bean" },
      { Radical: "⾗", Reading: "いのこ", Meaning: "pig" },
      { Radical: "⾘", Reading: "むじなへん", Meaning: "badger" },
      { Radical: "⾙", Reading: "かい", Meaning: "shell, property, wealth" },
      { Radical: "", Reading: "かいへん", Meaning: "shell, property, wealth" },
      { Radical: "⾚", Reading: "あか", Meaning: "red" },
      { Radical: "⾛", Reading: "はしる", Meaning: "to run" },
      { Radical: "", Reading: "そうにょう", Meaning: "to run" },
      { Radical: "⾜", Reading: "あし", Meaning: "foot, leg" },
      { Radical: "⻊", Reading: "あしへん", Meaning: "foot, leg" },
      { Radical: "⾝", Reading: "み", Meaning: "body" },
      { Radical: "", Reading: "みへん", Meaning: "body" },
      { Radical: "⾞", Reading: "くるま", Meaning: "vehicle, wheel, car" },
      { Radical: "", Reading: "くるまへん", Meaning: "vehicle, wheel, car" },
      { Radical: "⾟", Reading: "からい", Meaning: "bitter" },
      { Radical: "⾠", Reading: "しんのたつ", Meaning: "Fifth zodiac sign, 7–9 A.M." },
      { Radical: "⾡", Reading: "しんにょう", Meaning: "to advance, move ahead" },
      { Radical: "⾢", Reading: "むら", Meaning: "community" },
      { Radical: "⾣", Reading: "ひよみのとり", Meaning: "sake jar, bird" },
      { Radical: "", Reading: "とりへん", Meaning: "sake jar, bird" },
      { Radical: "⾤", Reading: "のごめ", Meaning: "to separate" },
      { Radical: "", Reading: "のごめへん", Meaning: "to separate" },
      { Radical: "⾥", Reading: "さと", Meaning: "village, (3.93 km)" },
      { Radical: "", Reading: "さとへん", Meaning: "village, (3.93 km)" },
      { Radical: "⾂", Reading: "しん", Meaning: "retainer, minister" },
      { Radical: "", Reading: "まいあし", Meaning: "contrary, to err" },
      { Radical: "⻨", Reading: "むぎ", Meaning: "wheat" },
      { Radical: "⾦", Reading: "かね", Meaning: "metal, gold, mineral" },
      { Radical: "", Reading: "かねへん", Meaning: "metal, gold, mineral" },
      { Radical: "⻑", Reading: "ながい", Meaning: "long" },
      { Radical: "⾨", Reading: "もんがまえ", Meaning: "gate, door" },
      { Radical: "⾩", Reading: "こざと", Meaning: "hill" },
      { Radical: "⾪", Reading: "れいづくり", Meaning: "to capture" },
      { Radical: "⾫", Reading: "ふるとり", Meaning: "small bird" },
      { Radical: "⾬", Reading: "あめ", Meaning: "rain" },
      { Radical: "⻗", Reading: "あめかんむり", Meaning: "rain" },
      { Radical: "⾭", Reading: "あお", Meaning: "blue, green" },
      { Radical: "⻘", Reading: "あお", Meaning: "blue, green"},
      { Radical: "⾮", Reading: "あらず", Meaning: "wrong, non-" },
      { Radical: "⻟", Reading: "しょくへん", Meaning: "food, to eat"},
      { Radical: "⻫", Reading: "せい", Meaning: "alike"},
      { Radical: "⾯", Reading: "めん", Meaning: "face, surface" },
      { Radical: "⾰", Reading: "つくりがわ", Meaning: "leather" },
      { Radical: "", Reading: "なめしがわ", Meaning: "leather" },
      { Radical: "⾲", Reading: "にら", Meaning: "leek" },
      { Radical: "⾳", Reading: "おと", Meaning: "sound, noise" },
      { Radical: "⾴", Reading: "おおがい", Meaning: "head, page"},
      { Radical: "⾵", Reading: "かぜ", Meaning: "wind" },
      { Radical: "⾶", Reading: "とぶ", Meaning: "to fly" },
      { Radical: "⾷", Reading: "しょく", Meaning: "food, to eat" },
      { Radical: "⾸", Reading: "くび", Meaning: "head" },
      { Radical: "⾹", Reading: "かおり", Meaning: "scent" },
      { Radical: "⾺", Reading: "うま", Meaning: "horse" },
      { Radical: "", Reading: "うまへん", Meaning: "horse"},
      { Radical: "⾻", Reading: "ほね", Meaning: "bone" },
      { Radical: "", Reading: "ほねへん", Meaning: "bone"},
      { Radical: "⾼", Reading: "たかい", Meaning: "high" },
      { Radical: "⾽", Reading: "かみかんむり", Meaning: "long hair" },
      { Radical: "⾾", Reading: "たたかいがまえ", Meaning: "fighting" },
      { Radical: "⾿", Reading: "においざけ", Meaning: "herbs" },
      { Radical: "⿀", Reading: "れき", Meaning: "tripod" },
      { Radical: "⿁", Reading: "おに", Meaning: "demon" },
      { Radical: "⾱", Reading: "なめしがわ", Meaning: "leather"},
      { Radical: "⿂", Reading: "うお", Meaning: "fish" },
      { Radical: "", Reading: "うおへん", Meaning: "fish"},
      { Radical: "⿃", Reading: "とり", Meaning: "bird" },
      { Radical: "⿄", Reading: "しお", Meaning: "salt" },
      { Radical: "⿅", Reading: "しか", Meaning: "deer" },
      { Radical: "⿆", Reading: "むぎ", Meaning: "wheat" },
      { Radical: "⿇", Reading: "あさ", Meaning: "hemp" },
      { Radical: "", Reading: "あさかんむり", Meaning: "hemp"},
      { Radical: "⻩", Reading: "き", Meaning: "yellow"},
      { Radical: "黒", Reading: "くろ", Meaning: "black"},
      { Radical: "⻲", Reading: "かめ", Meaning: "turtle"},
      { Radical: "⿈", Reading: "き", Meaning: "yellow" },
      { Radical: "⿉", Reading: "きび", Meaning: "millet" },
      { Radical: "⿊", Reading: "くろ", Meaning: "black" },
      { Radical: "⿋", Reading: "ぬいとり", Meaning: "embroider" },
      { Radical: "⻭", Reading: "は", Meaning: "tooth"},
      { Radical: "⿌", Reading: "かえる", Meaning: "frog" },
      { Radical: "⿍", Reading: "かなえ", Meaning: "tripod" },
      { Radical: "⿎", Reading: "つづみ", Meaning: "drum" },
      { Radical: "⿏", Reading: "ねずみ", Meaning: "rat, mouse" },
      { Radical: "⿐", Reading: "はな", Meaning: "nose" },
      { Radical: "⿑", Reading: "せい", Meaning: "alike" },
      { Radical: "⿒", Reading: "は", Meaning: "tooth" },
      { Radical: "⿓", Reading: "りゅう", Meaning: "dragon" },
      { Radical: "⿔", Reading: "かめ", Meaning: "turtle" },
      { Radical: "⿕", Reading: "やく", Meaning: "flute" } 
    ];
  
    const radicalsData = [
      { Radical: "一", Romaji: "ichi", Meaning: "one" },
      { Radical: "丨", Romaji: "bō", Meaning: "pole" },
      { Radical: "ヽ", Romaji: "ten", Meaning: "dot" },
      { Radical: "ノ", Romaji: "no", Meaning: "roof" },
      { Radical: "乙", Romaji: "otsu", Meaning: "hook" },
      { Radical: "乚", Romaji: "otsu", Meaning: "hook" },
      { Radical: "亅", Romaji: "hane", Meaning: "barb" },
      { Radical: "二", Romaji: "ni", Meaning: "two" },
      { Radical: "亠", Romaji: "nabeuta", Meaning: "lid" },
      { Radical: "人", Romaji: "hito", Meaning: "person" },
      { Radical: "亻", Romaji: "jin", Meaning: "person" },
      { Radical: "儿", Romaji: "naka", Meaning: "legs" },
      { Radical: "入", Romaji: "iri", Meaning: "enter" },
      { Radical: "八", Romaji: "hachi", Meaning: "eight" },
      { Radical: "冂", Romaji: "kyō", Meaning: "down box" },
      { Radical: "冖", Romaji: "mi", Meaning: "cover" },
      { Radical: "冫", Romaji: "hyō", Meaning: "ice" },
      { Radical: "几", Romaji: "kyo", Meaning: "table" },
      { Radical: "凵", Romaji: "kan", Meaning: "open box" },
      { Radical: "刀", Romaji: "katana", Meaning: "knife" },
      { Radical: "力", Romaji: "chikara", Meaning: "power" },
      { Radical: "勹", Romaji: "hō", Meaning: "wrap" },
      { Radical: "匕", Romaji: "sa", Meaning: "spoon" },
      { Radical: "匚", Romaji: "hako", Meaning: "box" },
      { Radical: "匸", Romaji: "kakushi", Meaning: "hide" },
      { Radical: "十", Romaji: "jū", Meaning: "ten" },
      { Radical: "卜", Romaji: "boku", Meaning: "divination" },
      { Radical: "卩", Romaji: "hane", Meaning: "seal" },
      { Radical: "厂", Romaji: "gai", Meaning: "cliff" },
      { Radical: "厶", Romaji: "shi", Meaning: "private" },
      { Radical: "又", Romaji: "mata", Meaning: "again" },
      { Radical: "口", Romaji: "kuchi", Meaning: "mouth" },
      { Radical: "囗", Romaji: "kunigamae", Meaning: "enclosure" },
      { Radical: "土", Romaji: "tsuchi", Meaning: "earth" },
      { Radical: "士", Romaji: "shi", Meaning: "samurai" },
      { Radical: "夂", Romaji: "tsugi", Meaning: "winter" },
      { Radical: "夊", Romaji: "sui", Meaning: "go" },
      { Radical: "夕", Romaji: "yū", Meaning: "evening" },
      { Radical: "大", Romaji: "dai", Meaning: "big" },
      { Radical: "女", Romaji: "onna", Meaning: "woman" },
      { Radical: "子", Romaji: "ko", Meaning: "child" },
      { Radical: "宀", Romaji: "mune", Meaning: "roof" },
      { Radical: "寸", Romaji: "sun", Meaning: "measurement" },
      { Radical: "小", Romaji: "shō", Meaning: "small" },
      { Radical: "尢", Romaji: "yō", Meaning: "lame" },
      { Radical: "尸", Romaji: "shikabane", Meaning: "corpse" },
      { Radical: "屮", Romaji: "tatsu", Meaning: "sprout" },
      { Radical: "山", Romaji: "yama", Meaning: "mountain" },
      { Radical: "川", Romaji: "kawa", Meaning: "river" },
      { Radical: "工", Romaji: "kō", Meaning: "work" },
      { Radical: "己", Romaji: "ono", Meaning: "self" },
      { Radical: "巾", Romaji: "kin", Meaning: "towel" },
      { Radical: "干", Romaji: "kan", Meaning: "dry" },
      { Radical: "幺", Romaji: "itoga", Meaning: "short thread" },
      { Radical: "广", Romaji: "madare", Meaning: "dotted cliff" },
      { Radical: "廴", Romaji: "en", Meaning: "prolonged" },
      { Radical: "廾", Romaji: "kazaru", Meaning: "two hands" },
      { Radical: "弋", Romaji: "shoku", Meaning: "shoot" },
      { Radical: "弓", Romaji: "yumi", Meaning: "bow" },
      { Radical: "彐", Romaji: "kei", Meaning: "pig" },
      { Radical: "彡", Romaji: "san", Meaning: "hair" },
      { Radical: "彳", Romaji: "chokkan", Meaning: "step" },
      { Radical: "心", Romaji: "kokoro", Meaning: "heart" },
      { Radical: "戈", Romaji: "hoko", Meaning: "spear" },
      { Radical: "戸", Romaji: "to", Meaning: "door" },
      { Radical: "手", Romaji: "te", Meaning: "hand" },
      { Radical: "支", Romaji: "shi", Meaning: "branch" },
      { Radical: "攴", Romaji: "boku", Meaning: "strike" },
      { Radical: "文", Romaji: "bun", Meaning: "script" },
      { Radical: "斗", Romaji: "to", Meaning: "dipper" },
      { Radical: "斤", Romaji: "kin", Meaning: "axe" },
      { Radical: "方", Romaji: "hō", Meaning: "direction" },
      { Radical: "旡", Romaji: "mu", Meaning: "not" },
      { Radical: "日", Romaji: "nichi", Meaning: "sun" },
      { Radical: "曰", Romaji: "ii", Meaning: "say" },
      { Radical: "月", Romaji: "getsu", Meaning: "moon" },
      { Radical: "木", Romaji: "ki", Meaning: "tree" },
      { Radical: "欠", Romaji: "ketsu", Meaning: "lack" },
      { Radical: "止", Romaji: "tomaru", Meaning: "stop" },
      { Radical: "歹", Romaji: "dai", Meaning: "death" },
      { Radical: "殳", Romaji: "hoko", Meaning: "weapon" },
      { Radical: "毌", Romaji: "kawa", Meaning: "mother" },
      { Radical: "比", Romaji: "hikusa", Meaning: "compare" },
      { Radical: "毛", Romaji: "ke", Meaning: "fur" },
      { Radical: "氏", Romaji: "uji", Meaning: "clan" },
      { Radical: "气", Romaji: "ki", Meaning: "steam" },
      { Radical: "水", Romaji: "mizu", Meaning: "water" },
      { Radical: "火", Romaji: "hi", Meaning: "fire" },
      { Radical: "爪", Romaji: "tsume", Meaning: "claw" },
      { Radical: "父", Romaji: "chichi", Meaning: "father" },
      { Radical: "爻", Romaji: "kai", Meaning: "crossroads" },
      { Radical: "爿", Romaji: "shinnyō", Meaning: "half tree" },
      { Radical: "片", Romaji: "hen", Meaning: "slice" },
      { Radical: "牙", Romaji: "kiba", Meaning: "fang" },
      { Radical: "牛", Romaji: "ushi", Meaning: "cow" },
      { Radical: "犬", Romaji: "inu", Meaning: "dog" },
      { Radical: "玄", Romaji: "gen", Meaning: "mysterious" },
      { Radical: "玉", Romaji: "gyoku", Meaning: "jewel" },
      { Radical: "瓜", Romaji: "uri", Meaning: "melon" },
      { Radical: "瓦", Romaji: "kawara", Meaning: "tile" },
      { Radical: "甘", Romaji: "amai", Meaning: "sweet" },
      { Radical: "生", Romaji: "sei", Meaning: "life" },
      { Radical: "用", Romaji: "yō", Meaning: "use" },
      { Radical: "田", Romaji: "ta", Meaning: "rice field" },
      { Radical: "疋", Romaji: "hiki", Meaning: "animal legs" },
      { Radical: "疒", Romaji: "yamaidare", Meaning: "illness" },
      { Radical: "癶", Romaji: "hatsu", Meaning: "depart" },
      { Radical: "白", Romaji: "shiro", Meaning: "white" },
      { Radical: "皮", Romaji: "kawa", Meaning: "skin" },
      { Radical: "皿", Romaji: "sara", Meaning: "dish" },
      { Radical: "目", Romaji: "me", Meaning: "eye" },
      { Radical: "矛", Romaji: "hoko", Meaning: "halberd" },
      { Radical: "矢", Romaji: "ya", Meaning: "arrow" },
      { Radical: "石", Romaji: "ishi", Meaning: "stone" },
      { Radical: "示", Romaji: "shimesu", Meaning: "show" },
      { Radical: "禸", Romaji: "gū", Meaning: "track" },
      { Radical: "禾", Romaji: "no", Meaning: "grain" },
      { Radical: "穴", Romaji: "ana", Meaning: "hole" },
      { Radical: "立", Romaji: "tatsu", Meaning: "stand" },
      { Radical: "竹", Romaji: "take", Meaning: "bamboo" },
      { Radical: "米", Romaji: "kome", Meaning: "rice" },
      { Radical: "糸", Romaji: "ito", Meaning: "thread" },
      { Radical: "缶", Romaji: "kan", Meaning: "can" },
      { Radical: "网", Romaji: "mou", Meaning: "net" },
      { Radical: "羊", Romaji: "hitsuji", Meaning: "sheep" },
      { Radical: "羽", Romaji: "hane", Meaning: "feather" },
      { Radical: "老", Romaji: "oi", Meaning: "old" },
      { Radical: "而", Romaji: "shikashite", Meaning: "and yet" },
      { Radical: "耒", Romaji: "suki", Meaning: "plow" },
      { Radical: "耳", Romaji: "mimi", Meaning: "ear" },
      { Radical: "聿", Romaji: "fude", Meaning: "brush" },
      { Radical: "肉", Romaji: "niku", Meaning: "meat" },
      { Radical: "臣", Romaji: "shin", Meaning: "minister" },
      { Radical: "自", Romaji: "ji", Meaning: "self" },
      { Radical: "至", Romaji: "ita", Meaning: "arrive" },
      { Radical: "臼", Romaji: "usu", Meaning: "mortar" },
      { Radical: "舌", Romaji: "shita", Meaning: "tongue" },
      { Radical: "舛", Romaji: "mai", Meaning: "oppose" },
      { Radical: "舟", Romaji: "fune", Meaning: "boat" },
      { Radical: "艮", Romaji: "gon", Meaning: "stopping" },
      { Radical: "色", Romaji: "shoku", Meaning: "color" },
      { Radical: "艸", Romaji: "kusa", Meaning: "grass" },
      { Radical: "虍", Romaji: "tora", Meaning: "tiger" },
      { Radical: "虫", Romaji: "mushi", Meaning: "insect" },
      { Radical: "血", Romaji: "chi", Meaning: "blood" },
      { Radical: "行", Romaji: "gyō", Meaning: "go" },
      { Radical: "衣", Romaji: "koromo", Meaning: "clothes" },
      { Radical: "西", Romaji: "nishi", Meaning: "west" },
      { Radical: "見", Romaji: "ken", Meaning: "see" },
      { Radical: "角", Romaji: "kaku", Meaning: "angle" },
      { Radical: "言", Romaji: "gen", Meaning: "say" },
      { Radical: "谷", Romaji: "tani", Meaning: "valley" },
      { Radical: "豆", Romaji: "mame", Meaning: "bean" },
      { Radical: "豕", Romaji: "buta", Meaning: "pig" },
      { Radical: "豸", Romaji: "mujina", Meaning: "badger" },
      { Radical: "貝", Romaji: "kai", Meaning: "shellfish" },
      { Radical: "赤", Romaji: "aka", Meaning: "red" },
      { Radical: "走", Romaji: "hashiru", Meaning: "run" },
      { Radical: "足", Romaji: "ashi", Meaning: "foot" },
      { Radical: "身", Romaji: "shin", Meaning: "body" },
      { Radical: "車", Romaji: "kuruma", Meaning: "car" },
      { Radical: "辛", Romaji: "karai", Meaning: "spicy" },
      { Radical: "辰", Romaji: "tatsu", Meaning: "dragon" },
      { Radical: "辵", Romaji: "shinnyō", Meaning: "walk" },
      { Radical: "邑", Romaji: "oku", Meaning: "city" },
      { Radical: "酉", Romaji: "tori", Meaning: "bird" },
      { Radical: "釆", Romaji: "bun", Meaning: "rice" },
      { Radical: "里", Romaji: "sato", Meaning: "village" },
      { Radical: "金", Romaji: "kin", Meaning: "gold" },
      { Radical: "長", Romaji: "naga", Meaning: "long" },
      { Radical: "門", Romaji: "mon", Meaning: "gate" },
      { Radical: "阜", Romaji: "takane", Meaning: "mound" },
      { Radical: "隶", Romaji: "reisho", Meaning: "slave" },
      { Radical: "隹", Romaji: "tori", Meaning: "bird" },
      { Radical: "雨", Romaji: "ame", Meaning: "rain" },
      { Radical: "青", Romaji: "ao", Meaning: "blue" },
      { Radical: "非", Romaji: "hi", Meaning: "negative" },
      { Radical: "面", Romaji: "men", Meaning: "face" },
      { Radical: "革", Romaji: "kawa", Meaning: "leather" },
      { Radical: "韋", Romaji: "i", Meaning: "tanned leather" },
      { Radical: "韭", Romaji: "nira", Meaning: "leek" },
      { Radical: "音", Romaji: "oto", Meaning: "sound" },
      { Radical: "頭", Romaji: "zukin", Meaning: "head" },
      { Radical: "頁", Romaji: "peiji", Meaning: "page" },
      { Radical: "風", Romaji: "kaze", Meaning: "wind" },
      { Radical: "飛", Romaji: "tobu", Meaning: "fly" },
      { Radical: "食", Romaji: "shoku", Meaning: "eat" },
      { Radical: "首", Romaji: "kubi", Meaning: "neck" },
      { Radical: "香", Romaji: "kō", Meaning: "fragrance" },
      { Radical: "馬", Romaji: "uma", Meaning: "horse" },
      { Radical: "骨", Romaji: "hone", Meaning: "bone" },
      { Radical: "高", Romaji: "taka", Meaning: "high" },
      { Radical: "髟", Romaji: "ke", Meaning: "hair" },
      { Radical: "鬥", Romaji: "tō", Meaning: "fight" },
      { Radical: "鬯", Romaji: "shu", Meaning: "liquor" },
      { Radical: "鬼", Romaji: "ki", Meaning: "demon" },
      { Radical: "魚", Romaji: "sakana", Meaning: "fish" },
      { Radical: "鳥", Romaji: "tori", Meaning: "bird" },
      { Radical: "鹵", Romaji: "shio", Meaning: "salt" },
      { Radical: "鹿", Romaji: "shika", Meaning: "deer" },
      { Radical: "麦", Romaji: "mugi", Meaning: "wheat" },
      { Radical: "麻", Romaji: "asa", Meaning: "hemp" },
      { Radical: "黄", Romaji: "ki", Meaning: "yellow" },
      { Radical: "黍", Romaji: "kibi", Meaning: "millet" },
      { Radical: "黒", Romaji: "kuro", Meaning: "black" },
      { Radical: "黹", Romaji: "nuu", Meaning: "embroidery" },
      { Radical: "黽", Romaji: "ao", Meaning: "frog" },
      { Radical: "鼎", Romaji: "kanae", Meaning: "tripod" },
      { Radical: "鼓", Romaji: "tsuzumi", Meaning: "drum" },
      { Radical: "鼠", Romaji: "nezumi", Meaning: "mouse" },
      { Radical: "鼻", Romaji: "hana", Meaning: "nose" },
      { Radical: "斉", Romaji: "sai, hitoshii", Meaning: "similar; 'Mr. Saito'" },
      { Radical: "歯", Romaji: "ha", Meaning: "tooth" },
      { Radical: "竜", Romaji: "tatsu", Meaning: "dragon, 'big dragon'" },
      { Radical: "亀", Romaji: "kame", Meaning: "turtle" },
      { Radical: "", Romaji: "fue", Meaning: "flute" }
    ];
    res.render('radicals/radicals_list', { user: req.user, radicals: radicalsData });
  } catch (err) {
    console.error(err);
    res.status(500).send('Server Error');
  }
};

exports.getRadicalsQuiz = async (req, res) => {
  try {
    res.render('radicals/radicals_quiz', { user: req.user });
  } catch (err) {
    console.error(err);
    res.status(500).send('Server Error');
  }
};